version: "3.9"
services:
  db:
    container_name: itrady-postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: itrady
    ports:
      - "5432:5432"
